.TH GOSERVE "1" "2013" "" ""


.SH "NAME"
goserve \- commandline web server.

.SH SYNOPSIS


.B goserve 
[
.B \-h
]
[
.B \--folder
]
[
.B \--index
]
[
.B \--port
]

Execute without arguments to start with default settings


.SH DESCRIPTION

Goserve is a minimal commandline server for web page hosting. It is primarily
used to host a single folder for a short period of time, with the intention of
debugging and viewing files in a browser.

.SH OPTIONS

  -h, --help             print the help information 

  --folder=folder        set the host folder        default: current folder

  --index=indexfile      set the index file         default: index.html 

  --port=port            set the index file         default: 3000


.SH RESOURCES AND DOCUMENTATION

See the website for documentation http://goserve.bech.pw/

See the git reposity for code and documentation: https://bitbucket.org/bech/goserve
